# BLANK CONFIG
[discord]
token = ''

[osu]
token = ''

[youtube]
api_key = ''
app_name = ''
callback_address = 'http://public_path_to_server'
callback_port = 8001
signing_key = 'any_secret_string'

[postgres]
connection_string = 'jdbc:postgresql://127.0.0.1/database?user=username&password=password'

[mongoDB]
address = '127.0.0.1'
port = 27017
username = ''
password = ''
auth_db = 'kizunaai'
bot_db = 'kizunaai'

[netty]
port = 8000
host = true
domain = 'http://public_path_to_server'

[twitch]
client_id = ''
client_secret = ''
chat_oauth_token = 'oauth:'
app_access_token = ''
callback = ''
twitch_signing_key = ''
twitch_webhook_port = 8003

[censor]
ip_services = [
    'http://checkip.amazonaws.com'
]

[admin]
admin_user = [
    83452231084412928
]
admin_channels = [
    582802415057633281
]
log_channel = 0

[twitter]
api_key = ''
api_key_secret = ''
bearer_token = ''

[microsoft]
translator_key = ''

[google]
gtranslator_key = ''

[ps2]
census_id = ''

[twitcasting]
twitcast_client_id = ''
twitcast_client_secret = ''
twitcast_webhook_port = 8002
twitcast_webhook_signature = ''
twitcast_webhook_listen = true